- README.md
Fixes #18 as well as a drive-by typo.
> A few tweaks to the README

- docusaurus.config.js
I tried this locally and the web page seemed to load faster than humanly-perceptible, so let's give it a go and see what people think.
(Spurred by the original post of https://github.com/pantsbuild/pantsbuild.org/issues/4 which had "The blog only seems to have 5 posts? http://docs.pantsbuild.org/blog")
> Render the entire blog on the blog page

- .github/workflows/sync_docs.yml
This does two minor adjustments to the PR that is created for syncing docs:
1. include a link to the relevant release (fixes #13)
2. assign a reviewer, by default the person triggering the workflow but can be overridden as an input (fixes #12)
Examples: #31 (default reviewer), #32 (providing reviewer input `thejcannon,huonw`)
> Assign assign reviewer & include link in doc sync PR

- old_site_redirects.js
This duplicates all the 2.18 readme redirect URLs, except without the `/v2.18/` bit. This is because readme supports these unversioned URLs, and in fact visiting the default website uses these unversioned version: thus, most URLs people have shared will be the unversioned ones  (and even visiting an explicitly versioned link with the current main version will redirect to these unversioned ones).
Fixes #5 (taking approach 2).
NB. if 2.19.0 is released before the switch-over, we'll want to revert this and redo it for 2.19. Process: find the segment with the versioned URLs with the version of interest, duplicate it and do a search replace to strip out `/v2.NN/`.
> Redirect from unversioned readme URLs to new 2.18.x

- .github/workflows/sync_docs.yml
This change fixes https://github.com/pantsbuild/pantsbuild.org/issues/42 by re-running the `help-all` command with every backend enabled. The list of backends is calculated by using all the keys of `.name_to_backend_help_info` from a run of `help-all`.
> Generate reference docs with all backends enabled

- docusaurus.config.js
Algolia was nice enough to crawl our site! :tada: 
Fixes https://github.com/pantsbuild/pantsbuild.org/issues/26
So now update the config with the relevant information.
Note we actually already have a search navbar item, but since we didn't configure search it wasn't rendered previously)
> Add search config

- .github/workflows/sync_docs.yml
This adjusts the Sync docs action to include the version in the "run-name" (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name), so that the Actions listing https://github.com/pantsbuild/pantsbuild.org/actions/workflows/sync_docs.yml is more informative:
> Include version in doc syncing run name

- .github/workflows/sync_docs.yml
This fixes the doc syncer now that we don't have `.x` in the directories (#48), per https://github.com/pantsbuild/pantsbuild.org/pull/48#issuecomment-1876073051
It also makes an unrelated fix, so that my test works.
Test: #57, https://github.com/pantsbuild/pantsbuild.org/actions/runs/7403672327/job/20143898054
> Fix doc syncing for `.x` removal

- docusaurus.config.js
I have a small suspicion this is why https://github.com/pantsbuild/pantsbuild.org/issues/45 is happening.
See the sitemap.xml: https://docs.pantsbuild.org/sitemap.xml
> Update the URL

- package.json
- reference_codegen/generate.mjs
This does a bunch of leg work to have the reference files be reformatted (with prettier) as they are written.  This makes the generation notably slower (slightly less than 1s -> slightly less than 4s on my machine), but saves from having to remember to run the formatting separately... which takes just as long as the extra time anyway.
This requires a few steps, broken across commits in a useful way (with some not-strictly-necessary changes), because prettier only has an async API. This seems to require running as an `.mjs` ("module") rather than `.js` to be able to use `await` at the top level.
After getting to using async + prettier, this then makes a few changes that this allows:
- a neater way to write the JSON files
- writing all files concurrently with `Promise.all` (writing the …
> Run prettier on reference files as they are generated

- .github/workflows/ci.yml
- package.json
This does a basic version of validating that the checked-in reference docs are valid, i.e. regenerating them gives the same result. It does this by just running the generation and checking that there's no changes.
This ensures that we don't, for instance, make a change to the templates and then forget to regenerate everything.
> Check reference docs are up to date in CI

- docusaurus.config.js
This adjusts the "copyright" section of the website footer to include:
- a link to this repository, replacing the "built with docusaurus" text, since that can be discovered by clicking through to the repo (it be fine to continue to include that if required).
- a reference to which commit the deployed website is showing, so we can be sure we're looking at what we expect (it would be fine to move this to a HTML comment instead, so it's just available for reference in the rare case it's required).
Example:
> Include link to pantsbuild.org repo and commit in footer

- src/components/reference/Option.jsx
Fixes https://github.com/pantsbuild/pantsbuild.org/issues/69 by adding links to references to `_environment` targets.
Ran locally and verified the links work as expected.
> Add links to `_environment` targets in options component

- docusaurus.config.js
This change does 2 things (both of which fixes #https://github.com/pantsbuild/pantsbuild.org/issues/78)
- Removes edit URL on reference docs
- Changes the URL on the docs docs to `main` branch on the `pants` repo
- NB This change is nonsensical until after the switchover
> Change `editURL` to a function

- docusaurus.config.js
- src/js/redirectCodeFragment.js
As an alternative to https://github.com/pantsbuild/pantsbuild.org/pull/55 and to fix #6, and pulled from option 4 of https://github.com/pantsbuild/pantsbuild.org/issues/6#issuecomment-1872622556, add a little JS to the React router that redirects `#code...code` fragments on reference pages.
Tested locally (`npm start`), and verified the "back" button doesn't go back to the `code` fragment URL but rather the URL before that.
> Redirect `#code...code` fragments

- .github/workflows/sync_docs.yml
Otherwise, we open PRs with the default bot, which can't trigger PR CI :cry:
> Use WorkerPants PAT for PRs

- docusaurus.config.js
- src/js/docsPluginWithTopLevel404.js
Fixes https://github.com/pantsbuild/pantsbuild.org/issues/7 in an unfortunately clever, yet still appropriate way.
See the comment in `src/js/docsPluginWithTopLevel404.js` for greater detail.
Tests:
- http://localhost:3000 -> :heavy_check_mark: 
- http://localhost:3000/ -> (redirects to http://localhost:3000)
- http://localhost:3000/2.20/docs/introduction/welcome-to-pants -> :heavy_check_mark: 
- http://localhost:3000/2.20/nope -> (Page Not Found) :heavy_check_mark: 
- http://localhost:3000/nope -> (Page Not Found) :heavy_check_mark: 
- http://localhost:3000/sponsorship -> :heavy_check_mark:
> Fix blank top-level 404 page

- docusaurus.config.js
This seems to be an oversight, as we are using the code metadata for these tabs.
Fixes https://github.com/pantsbuild/pantsbuild.org/issues/98
> Add `tabBlocks` remark plugin

- .github/workflows/sync_docs.yml
I plan on putting docs at `docs/docs` so we can put extra stuff in `docs/` (like a README)
> Sync from `docs/docs` on the Pants repo

- blog/2021-08-02-introducing-pants-2-6/index.mdx
- blog/2021-09-27-contributing-yapf-support/index.mdx
- blog/2022-09-01-introducing-pants-2-13/index.mdx
- blog/2023-02-24-pants-2-15/index.mdx
- blog/2023-03-02-write-or-speak-about-pants-communitys-favorite-topics/index.mdx
This adjusts all blog posts that have multiple `<h1>` headings to instead not have multiple, by bumping those duplicates to `<h2>` (and so on, for any nested headings).
Related to #112, picked out of #117.
> Avoid duplicate h1 headings in blog posts

- .github/workflows/sync_docs.yml
This change makes it so the `sync_docs` workflow has an extra step that turns `docs/` into `versioned_docs/<version>` if the release is a0.
The following steps should sync the `a0` release into the newly created directory.
This aligns with our release process, where `a0` is a new stable branch: https://www.pantsbuild.org/2.18/docs/contributions/releases/release-process#a0---create-a-new-git-branch
> When syncing, make the a0 release create a new version

- .github/workflows/sync_docs.yml
The sync-docs action failed for 2.19.0 (https://github.com/pantsbuild/pantsbuild.org/actions/runs/7672731834/job/20913871609) and it looks like this is the issue.
> add missing `then`

- docusaurus.config.js
This ensures that when we release a version, it'll not tag it as a prerelease.
> Use `help-all.json` to label prereleases in version selector

- docusaurus.config.js
Noticed that if you go to `pantsbuild.org` in a clean browsing session it'll still go to 2.18, because this defaults to index 1 still.
> check prerelease for lastVersion

- docusaurus.config.js
- src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
Fixes a few issues:
* We have checked in rc versions for 2.17 and 2.16, which meant they got labeled as pre-release. I opted to only treat `.0` versions as pre-release here to have a sensible lable even if we accidentally sync pre-release docs later
* I also noted that we showed two deprecated versions in the dropdown, we'll now cut off one more item if the first entry is prerelease as showing two deprecated versions seemed excessive
* Also fixed so the unmaintained banner shows up properly
* For consistency I did the same change to `noIndex` field but i've no idea what that does practically. Search indexing? Google? All?
> Fix deprecated version inconsistencies

- README.md
The docs currently suggest `npm build` which doesn't work with npm v8.6.0, which is what my system uses with node 18.
> Suggest `npm run build` in docs

- .github/workflows/ci.yml
This has PR CI upload the resulting static site output, once the build finishes.
This is a stop gap for https://github.com/pantsbuild/pantsbuild.org/issues/28 that's seems like it's better than nothing: to preview a PR, click through to the build summary, download the artifact and take a look. This saves a reviewer from needing to check-out the branch and build it, just do a (100MB) download instead.
> Upload build from PR CI for easier previewing

- docusaurus.config.js
https://www.pantsbuild.org/community/getting-help seems to currently only be linked from the synced docs/reference, but might be nice to have in the footer too?
> Add link to "Getting Help" to footer

- .github/workflows/sync_docs.yml
Minor typo in the check for alpha versions meant it didn't trigger: it's intending to search for `2.x.0a0`, i.e. first alpha version leading up to the first stable release in `2.x` series... but missed the 0 between the `.` and the `a`.
This explains (https://github.com/pantsbuild/pantsbuild.org/pull/162#issuecomment-1968056882): why we don't have a `versioned_docs/version-2.20` directory despite #153  landing.
This PR doesn't create that directory, just fixing the bug in the automation. I've retriggered the sync from this PR's branch to do that: #164
> Check for .0a0 for new version creation, not .a0

- src/pages/_index.mdx
This papers over the dead "Learn more" link on the pantsbuild.org front page (https://github.com/pantsbuild/pants/issues/20648) by replacing it with the hard-coded `/2.19/docs/introduction/welcome-to-pants`, for the current latest-stable version.
This isn't a full solution: preferably this would be a "dynamic" link, pointing to the latest stable version. Thus this doesn't close that issue.
The dynamic approach we take in some other pages isn't perfect because it isn't to the latest _stable_ release, but can include pre-releases (it [currently](https://www.pantsbuild.org/community/members#how-can-i-contribute-to-pants) points to `/2.20/...`, which is probably reasonable for a contributing guide, but less so for a "getting started" one): …
> Replace front-page "learn more" link with hard-coded 2.19 one

- README.md
This repository is a bit confusing, with the large quantity of auto-generated don't-edit per-version documentation files in `docs/` and `versioned_docs/`. This PR augments the README with a short explanation of what's where and how to make changes.
(It may need changes in future, depending on what happens with #148.)
> Document which types of content are where, and how to edit them

- docusaurus.config.js
The goal here is to centralise the logic around versions, creating a list of all the details about each version (e.g. full version number, whether it's a pre-release or unmaintained etc.), that downstream processing can reference directly rather than recompute. This, for instance, eliminates the duplicated logic around which versions are maintained.
The goal here is to make changes like #174 (and maybe #159) easier. This PR doesn't/shouldn't change observable behaviour.
This also removes the explicit `disableVersioning` flag, since that seems to require changing the contents of the `versions` map. Instead the existing use of `onlyIncludeVersions` seems to do what's intended: make dev builds faster. An `npm start` build takes about 10s both with the old `disableVersioning` setting, or just …
> Centralise versioning configuration

- src/components/VersionedDocsLink.jsx
- src/pages/_index.mdx
- src/pages/community/members.mdx
This PR fixes #174 with a new `VersionedDocsLink` component that reads the docusaurus config to determine what the latest stable version is.
It also adjusts the other dynamic link to the contribution guide to use this. This link is changed from the latest RC versions (currently 2.20) to the current `main` version (2.21), i.e. the absolute most up-to-date version of the contribution guide, which seems most relevant to contributors since they'll be starting in the `main` branch.
This has a few issues with the component due to https://github.com/prettier/prettier/issues/12209, which forces us into a very long line on the `_index.mdx` page.
I'm unclear if a broken link will be detected or not.
> Add VersionedDocsLink and use for evergreen links to "latest" docs page

- .github/workflows/sync_docs.yml
https://github.com/pantsbuild/pants/issues/20315 is now fixed (in https://github.com/pantsbuild/scie-pants/pull/375 / https://github.com/pantsbuild/scie-pants/releases/tag/v0.10.8), so the sync_docs workflow can be slightly slicker.
> Invoke pants help-all twice, not thrice

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- README.md
It appears that we need more memory to build after branching for 2.21: the update that splits it (#193) is failing due to running out of memory.
This bumps to 12GiB, slightly less than the runner's RAM (16GB).
(#196 validates that this does actually fix it for 2.21.)
> Increase --max-old-space-size option for 2.21

- blog/2021-05-20-introducing-pants-2-5/index.mdx
- blog/2021-08-02-introducing-pants-2-6/index.mdx
- blog/2021-09-27-introducing-pants-2-7/index.mdx
- blog/2021-11-17-introducing-pants-2-8/index.mdx
- blog/2022-03-23-introducing-pants-2-10/index.mdx
- blog/2022-05-02-introducing-pants-2-11/index.mdx
- blog/2022-09-01-introducing-pants-2-13/index.mdx
- blog/2023-02-24-pants-2-15/index.mdx
- blog/2023-06-16-pants-2-16-0/index.mdx
- blog/2023-08-30-pants-2-17-0-is-released/index.mdx
Not sure if anything here is generated, but didn't look like it. I couldn't find a perfect tag that followed the minor so I went with the release one. Maybe you want them to target the latest patch for each, but I also assume most/all of these will not be updated anymore anyways.
> Fix dead changelog links in blog posts

- blog/authors.yml
In the blogpost I authored last year, the link to my GitHub handle is wrong:
So this PR corrects that :slightly_smiling_face:
> Blog: fix wrong GitHub handle

- blog/2021-09-27-introducing-pants-2-7/index.mdx
- blog/2022-06-29-pants-2-12/index.mdx
- blog/2022-10-26-pants-2-14/index.mdx
This rewrites the old `src/python/pants/notes` path for changelogs to `docs/notes` in three blog posts.
Fixes #209  (together with #222)
There's still some references to the ``src/python/pants/notes`` path in this repo, but I don't think they need updating. They either:
- have a branch or tag reference that has the notes in the old location, e.g. https://github.com/pantsbuild/pantsbuild.org/blob/67038eb6956fe4c8fc956884897efebac6e8fd8d/blog/2023-11-14-pants-2.18.0-is-released/index.mdx#L99
- are in old reference docs, and seems like it can be adequately handled via the redirects we now have: https://github.com/pantsbuild/pants/pull/20937 (alternatively, we _could_ rewrite them)
> Fix `main` branch links to changelogs, in blog posts

- src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
- yarn.lock
I don't have any fancy Javascript skills, I just blindly ran `yarn upgrade` to bump everything in the lockfile since I was annoyed by the upgrade warnings.
Release highlights (each links to detailed changelogs):
* https://docusaurus.io/blog/releases/3.1
* https://docusaurus.io/blog/releases/3.2
* https://docusaurus.io/blog/releases/3.3
* https://docusaurus.io/blog/releases/3.4
* https://docusaurus.io/blog/releases/3.5
> update Docusaurus to 3.5

- .github/workflows/deploy.yml
- README.md
- docusaurus.config.js
Currently all of the versioned docs have the explicit version in the url.  This has the virtue of being
[cool](https://www.w3.org/Provider/Style/URI) but has some awkwardness in practice.  For example if one links to
https://www.pantsbuild.org/2.18/docs/using-pants/using-pants-in-ci from another webpage it will eventualy end up with the 'no longer maintained' banner.  It isn't super fun to update every internal/wiki link every 6 weeks for a release.
This change introduces some "semi-stable" urls for key versions:
* `prerelease`: The latest prerelease
* `dev`: aka `main` aka "trunk"
* `stable`: The most recent stable release
Redirects ensure that the versioned urls also work.
As an example, right now:
`/stable/docs/using-pants/using-pants-in-ci` is the doc for `2.21` and …
> use friendly "semi-stable" urls for key versions

- docusaurus.config.js
Followup to 6136389.  The redirect for /stable and /dev worked, but not /prerelease.
Test on fully built site:
```
$ curl http://localhost:3000/2.22/docs/introduction/welcome-to-pants
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url=/prerelease/docs/introduction/welcome-to-pants">
<link rel="canonical" href="/prerelease/docs/introduction/welcome-to-pants" />
</head>
<script>
window.location.href = '/prerelease/docs/introduction/welcome-to-pants' + window.location.search + window.location.hash;
</script>
```
> detect mostRecentPreReleaseVersion in a way that actually works

- versioned_docs/version-2.22/reference/global-options.mdx
- versioned_docs/version-2.22/reference/goals/export.mdx
- versioned_docs/version-2.22/reference/subsystems/google-java-format.mdx
- versioned_docs/version-2.22/reference/subsystems/jarjar.mdx
- versioned_docs/version-2.22/reference/subsystems/java-avro.mdx
- versioned_docs/version-2.22/reference/subsystems/junit.mdx
- versioned_docs/version-2.22/reference/subsystems/ktlint.mdx
- versioned_docs/version-2.22/reference/subsystems/openapi-generator.mdx
- versioned_docs/version-2.22/reference/subsystems/protobuf-java-grpc.mdx
- versioned_docs/version-2.22/reference/subsystems/scalafix.mdx
- versioned_docs/version-2.22/reference/subsystems/scalafmt.mdx
- versioned_docs/version-2.22/reference/subsystems/scalapb.mdx
- versioned_docs/version-2.22/reference/subsystems/scalatest.mdx
- versioned_docs/version-2.22/reference/subsystems/scrooge.mdx
- versioned_docs/version-2.22/reference/targets/jvm_artifact.mdx
- versioned_docs/version-2.22/reference/targets/pants_requirements.mdx
- versioned_docs/version-2.22/reference/targets/python_requirement.mdx
- versioned_docs/version-2.22/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.22.0
> Update docs site for version 2.22.0

- blog/2024-08-24-venerable-pythons/index.mdx
See https://github.com/pantsbuild/pants/issues/21103
> update 3.7 deprecation blog post to reflect actual schedule

- docusaurus.config.js
- src/css/custom.css
Add an announcement bar to announce the 2024 Pantsbuild User Survey. I added some custom styles to (1) make the text larger and (2) to restore default link colors.
Screenshot:
> add announcement bar for the 2024 User Survey

- src/css/custom.css
The CSS class names applied to the Docusaurus announcement bar in production has different casing than in development. Use the case-insensitive CSS selector option so the custom CSS styling matches both environments.
> use case-insensitive match for CSS selectors in production

- src/pages/community/getting-help.mdx
Lay out expectations for how to ask for help.
> Augment Getting Help docs.

- versioned_docs/version-2.23/docs/contributions/releases/github-actions-linux-aarch64-runners.mdx
- versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx
- versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx
- versioned_docs/version-2.23/reference/subsystems/jarjar.mdx
- versioned_docs/version-2.23/reference/subsystems/java-avro.mdx
- versioned_docs/version-2.23/reference/subsystems/java-parser.mdx
- versioned_docs/version-2.23/reference/subsystems/junit.mdx
- versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx
- versioned_docs/version-2.23/reference/subsystems/ktlint.mdx
- versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx
- versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx
- versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx
- versioned_docs/version-2.23/reference/subsystems/scalafix.mdx
- versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx
- versioned_docs/version-2.23/reference/subsystems/scalapb.mdx
- versioned_docs/version-2.23/reference/subsystems/scalatest.mdx
- versioned_docs/version-2.23/reference/subsystems/scrooge.mdx
- versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx
- versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx
- versioned_docs/version-2.23/reference/targets/pants_requirements.mdx
- versioned_docs/version-2.23/reference/targets/python_requirement.mdx
- versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.0rc1
> Update docs site for version 2.23.0rc1

- .github/workflows/sync_docs.yml
This makes us more likely to notice problems in the automatic doc syncing like #284 earlier, by surfacing the failures as PRs, not just hidden in the actions UI.
The doc syncing usually happens automagically as part of the release process, in the background. If it fails, this is only visible in two ways:
- implicitly, in the lack of <https://github.com/pantsbuild/pantsbuild.org/labels/automation%3Async-docs>-labelled PR
- by noticing the failure on the actions page: https://github.com/pantsbuild/pantsbuild.org/actions/workflows/sync_docs.yml
Both of these are easy to miss (very easy to miss that something that should happen didn't happen, and the actions page is only rarely visited!). There's no progress updates/reminder about the doc sync, nor is there a notification on failure. 
In …
> Make sync_docs failures noisier by always posting a PR

- blog/2024-09-10-pants-2-22/index.mdx
- blog/2024-11-20-pants-2-23/index.mdx
The old link pointed to a nonexistent page.
Also fix links in the 2.22.0 post that 2.23.0 was
copy-pasta'd from. Those links weren't broken,
but they led to a redirection page, so might as
well point them to the target location.
> Fix links to release notes in 2.23.0 blog post.

- src/pages/spotlight/testimonials.mdx
- src/pages/spotlight/users.mdx
This fixes two links that were previously explicitly pointing at the 404 page, after the migration from the old site:
- the "Add your organization or company" link on the user spotlight page, which used to point to https://pantsbuild.org/register : this still works (appears to be 301 redirect configured in CloudFlare?), and redirects to a GitHub issue template.
- the "Add your testimionial" link on the testimonials page, which didn't previously exist (https://web.archive.org/web/20230604011655/https://www.pantsbuild.org/docs/testimonials). I've hidden this one to at least not have a wildly broken link in people's face, but we can restore it once we have an appropriate process. (Although I imagine most people looking at the testimonials page will be _new_ users, i.e. not in a position to …
> Fix "Add your org" link, hide "Add your testimonial" one

- docusaurus.config.js
The 2024 user survey is now closed so remove the announcement bar link to it.
> remove announcement bar link to the now-closed user survey

- .github/workflows/deploy.yml
The last docs update failed with:
https://github.com/pantsbuild/pantsbuild.org/actions/runs/12934911051/job/36077004632
```
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Download action repository 'actions/setup-node@v3' (SHA:1a4442cacd436585916779262731d5b162bc6ec7)
Download action repository 'actions/cache@v3' (SHA:f4b3439a656ba812b8cb417d2d49f9c810103092)
Download action repository 'actions/configure-pages@v3' (SHA:b8130d9ab958b325bbde9786d62f2c97a9885a0e)
Download action repository 'actions/upload-pages-artifact@v2' (SHA:a753861a5debcf57bf8b404356158c8e1e33150c)
Download action repository 'actions/deploy-pages@v2' (SHA:de14547edc9944350dc0481aa5b7afb08e75f254)
Getting action download info
Error: This …
```
> update to the latest pages action so that it might work again

- .github/workflows/deploy.yml
This is followup to #311
Per
https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0 `actions/upload-pages-artifact@3` requires `actions/deploy-pages@v4`
> update GitHub Actions... more

- src/pages/sponsors.mdx
They have decided to end their sponsorship.
> Remove Normal Computing from sponsors page.

- babel.config.js
- docusaurus.config.js
- package.json
- yarn.lock
Closes #359 
See: https://docusaurus.io/blog/releases/3.8
Also added `v4: true` to (hopefully) take advantage of Node worker threads for static site generation.
From actions, the cold build was similar to the cached builds of previous iterations. After removing module concatenation, the `build` time is under 5 minutes (3x faster than cold builds). 
There will be additional PRs with caching/CI updates, but this feels like a good start. 
```bash
build-original % find . | wc -l
33124
build-original % du -hs 
703M	.
build-faster % find . | wc -l
33122
build-faster % du -hs 
656M	.
build-faster-concat % find . | wc -l 
33122
build-faster-concat % du -hs 
656M	.
```
The 2 missing files are in the ./assets/js outputs - and both are LICENSE files.
To test what the effect the `concatenateModules` …
> Updated Docusaurus to 3.8 and enabled `docusaurus/faster`

- src/pages/spotlight/users.mdx
> Replaced broken `register` link with one to Github's registration template

- docusaurus.config.js
- renamed_path_redirects.js
Uses this to provide redirects required by
https://github.com/pantsbuild/pants/pull/20544
> Support for redirects other than the old site ones.
