pantsbuild/pantsbuild.org

.github/workflows/ci.yml, package.json
Fixes https://github.com/pantsbuild/pantsbuild.org/issues/20 by adding (and using) a new `check-formatting` script and using it.
=> Fix broken PR CI

docusaurus.config.js
=> Fix "whos" -> "who's" typo

docusaurus.config.js
Let's not tease functionality that doesn't exist, while we wait for Algolia to get back to us (#26).
Fixes #15
=> Hide "search coming soon" for now

docusaurus.config.js
I regenerated our key in an attempt to get search working
=> Update Algolia API key

reference_codegen/generate.mjs
See https://github.com/pantsbuild/pantsbuild.org/pull/71#discussion_r1444935188
=> Ensure `dynamic_ui` always has a `True` default

docusaurus.config.js
=> Let's go live!

src/theme/NotFound/Content/index.jsx
Fixes #88 by swizzling `NotFound/Content`
The important thing to me was catching `/v1` URLs
=> Render a nicer 404

src/pages/sponsorship.mdx, src/pages/spotlight/jobs.mdx
I split this out of the work in https://github.com/pantsbuild/pantsbuild.org/pull/116 to be in its own PR.
=> Fix multiple h1 headers in pages/

src/pages/community/members.mdx, src/pages/sponsorship.mdx
Fixes https://github.com/pantsbuild/pantsbuild.org/issues/107 and fixes https://github.com/pantsbuild/pantsbuild.org/issues/111
=> Fix a few links in pages

docs/docs/contributions/releases/github-actions-macos-arm64-runners.mdx, docs/docs/contributions/releases/release-process.mdx, docs/docs/docker/index.mdx, docs/docs/using-pants/using-pants-in-ci.mdx, docs/reference/subsystems/google-java-format.mdx, docs/reference/subsystems/jarjar.mdx, docs/reference/subsystems/java-avro.mdx, docs/reference/subsystems/junit.mdx, docs/reference/subsystems/ktlint.mdx, docs/reference/subsystems/openapi-generator.mdx, docs/reference/subsystems/pex-cli.mdx, docs/reference/subsystems/protobuf-java-grpc.mdx, docs/reference/subsystems/python.mdx, docs/reference/subsystems/scalafix.mdx, docs/reference/subsystems/scalafmt.mdx, docs/reference/subsystems/scalapb.mdx, docs/reference/subsystems/scalatest.mdx, docs/reference/subsystems/scrooge.mdx, docs/reference/targets/jvm_artifact.mdx, docs/reference/targets/pants_requirements.mdx, docs/reference/targets/python_requirement.mdx, docs/reference/targets/python_source.mdx, docs/reference/targets/python_sources.mdx, docs/reference/targets/python_test.mdx, docs/reference/targets/python_test_utils.mdx, docs/reference/targets/python_tests.mdx, docs/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.0.dev1
=> Update docs site for version 2.21.0.dev1

versioned_docs/version-2.19/docs/contributions/development/style-guide.mdx, versioned_docs/version-2.19/docs/contributions/releases/release-process.mdx, versioned_docs/version-2.19/docs/python/overview/lockfiles.mdx, versioned_docs/version-2.19/docs/shell/run-shell-commands.mdx, versioned_docs/version-2.19/docs/terraform/_category_.json, versioned_docs/version-2.19/docs/using-pants/setting-up-an-ide.mdx, versioned_docs/version-2.19/reference/goals/export.mdx, versioned_docs/version-2.19/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.19/reference/subsystems/jarjar.mdx, versioned_docs/version-2.19/reference/subsystems/java-avro.mdx, versioned_docs/version-2.19/reference/subsystems/junit.mdx, versioned_docs/version-2.19/reference/subsystems/ktlint.mdx, versioned_docs/version-2.19/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.19/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.19/reference/subsystems/pydocstyle.mdx, versioned_docs/version-2.19/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.19/reference/subsystems/scalapb.mdx, versioned_docs/version-2.19/reference/subsystems/scalatest.mdx, versioned_docs/version-2.19/reference/subsystems/scrooge.mdx, versioned_docs/version-2.19/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.19/reference/targets/pants_requirements.mdx, versioned_docs/version-2.19/reference/targets/python_requirement.mdx, versioned_docs/version-2.19/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.19.1
=> Update docs site for version 2.19.1

docs/docs/using-pants/key-concepts/options.mdx, docs/reference/subsystems/google-java-format.mdx, docs/reference/subsystems/jarjar.mdx, docs/reference/subsystems/java-avro.mdx, docs/reference/subsystems/junit.mdx, docs/reference/subsystems/ktlint.mdx, docs/reference/subsystems/openapi-generator.mdx, docs/reference/subsystems/protobuf-java-grpc.mdx, docs/reference/subsystems/scalafix.mdx, docs/reference/subsystems/scalafmt.mdx, docs/reference/subsystems/scalapb.mdx, docs/reference/subsystems/scalatest.mdx, docs/reference/subsystems/scrooge.mdx, docs/reference/targets/jvm_artifact.mdx, docs/reference/targets/pants_requirements.mdx, docs/reference/targets/python_requirement.mdx, docs/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.0.dev2
=> Update docs site for version 2.21.0.dev2

versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/pex-cli.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.0rc1
=> Update docs site for version 2.20.0rc1

versioned_docs/version-2.20/docs/using-pants/remote-caching-and-execution/remote-caching.mdx, versioned_docs/version-2.20/reference/goals/export.mdx, versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/pex.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.0rc2
=> Update docs site for version 2.20.0rc2

versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.0rc3
=> Update docs site for version 2.20.0rc3

versioned_docs/version-2.19/reference/goals/export.mdx, versioned_docs/version-2.19/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.19/reference/subsystems/jarjar.mdx, versioned_docs/version-2.19/reference/subsystems/java-avro.mdx, versioned_docs/version-2.19/reference/subsystems/junit.mdx, versioned_docs/version-2.19/reference/subsystems/ktlint.mdx, versioned_docs/version-2.19/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.19/reference/subsystems/pex-cli.mdx, versioned_docs/version-2.19/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.19/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.19/reference/subsystems/scalapb.mdx, versioned_docs/version-2.19/reference/subsystems/scalatest.mdx, versioned_docs/version-2.19/reference/subsystems/scrooge.mdx, versioned_docs/version-2.19/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.19/reference/targets/pants_requirements.mdx, versioned_docs/version-2.19/reference/targets/python_requirement.mdx, versioned_docs/version-2.19/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.19.2
=> Update docs site for version 2.19.2

versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.0rc4
=> Update docs site for version 2.20.0rc4

versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.0
=> Update docs site for version 2.20.0

versioned_docs/version-2.20/docs/using-pants/key-concepts/targets-and-build-files.mdx, versioned_docs/version-2.20/docs/using-pants/remote-caching-and-execution/remote-caching.mdx, versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.1
=> Update docs site for version 2.20.1

versioned_docs/version-2.21/docs/using-pants/key-concepts/targets-and-build-files.mdx, versioned_docs/version-2.21/docs/using-pants/remote-caching-and-execution/remote-caching.mdx, versioned_docs/version-2.21/reference/goals/export.mdx, versioned_docs/version-2.21/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.21/reference/subsystems/jarjar.mdx, versioned_docs/version-2.21/reference/subsystems/java-avro.mdx, versioned_docs/version-2.21/reference/subsystems/junit.mdx, versioned_docs/version-2.21/reference/subsystems/ktlint.mdx, versioned_docs/version-2.21/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.21/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.21/reference/subsystems/scalafix.mdx, versioned_docs/version-2.21/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.21/reference/subsystems/scalapb.mdx, versioned_docs/version-2.21/reference/subsystems/scalatest.mdx, versioned_docs/version-2.21/reference/subsystems/scrooge.mdx, versioned_docs/version-2.21/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.21/reference/targets/pants_requirements.mdx, versioned_docs/version-2.21/reference/targets/python_requirement.mdx, versioned_docs/version-2.21/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.0a1
=> Update docs site for version 2.21.0a1

versioned_docs/version-2.21/docs/jvm/java-and-scala.mdx, versioned_docs/version-2.21/docs/writing-plugins/common-subsystem-tasks.mdx, versioned_docs/version-2.21/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.21/reference/subsystems/jarjar.mdx, versioned_docs/version-2.21/reference/subsystems/java-avro.mdx, versioned_docs/version-2.21/reference/subsystems/junit.mdx, versioned_docs/version-2.21/reference/subsystems/ktlint.mdx, versioned_docs/version-2.21/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.21/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.21/reference/subsystems/scalafix.mdx, versioned_docs/version-2.21/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.21/reference/subsystems/scalapb.mdx, versioned_docs/version-2.21/reference/subsystems/scalatest.mdx, versioned_docs/version-2.21/reference/subsystems/scrooge.mdx, versioned_docs/version-2.21/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.21/reference/targets/pants_requirements.mdx, versioned_docs/version-2.21/reference/targets/python_requirement.mdx, versioned_docs/version-2.21/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.0rc0
=> Update docs site for version 2.21.0rc0

versioned_docs/version-2.19/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx, versioned_docs/version-2.19/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.19/reference/subsystems/jarjar.mdx, versioned_docs/version-2.19/reference/subsystems/java-avro.mdx, versioned_docs/version-2.19/reference/subsystems/junit.mdx, versioned_docs/version-2.19/reference/subsystems/ktlint.mdx, versioned_docs/version-2.19/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.19/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.19/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.19/reference/subsystems/scalapb.mdx, versioned_docs/version-2.19/reference/subsystems/scalatest.mdx, versioned_docs/version-2.19/reference/subsystems/scrooge.mdx, versioned_docs/version-2.19/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.19/reference/targets/pants_requirements.mdx, versioned_docs/version-2.19/reference/targets/python_requirement.mdx, versioned_docs/version-2.19/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.19.3
=> Update docs site for version 2.19.3

versioned_docs/version-2.20/docs/jvm/java-and-scala.mdx, versioned_docs/version-2.20/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx, versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.2
=> Update docs site for version 2.20.2

versioned_docs/version-2.21/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx, versioned_docs/version-2.21/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.21/reference/subsystems/jarjar.mdx, versioned_docs/version-2.21/reference/subsystems/java-avro.mdx, versioned_docs/version-2.21/reference/subsystems/junit.mdx, versioned_docs/version-2.21/reference/subsystems/ktlint.mdx, versioned_docs/version-2.21/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.21/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.21/reference/subsystems/scalafix.mdx, versioned_docs/version-2.21/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.21/reference/subsystems/scalapb.mdx, versioned_docs/version-2.21/reference/subsystems/scalatest.mdx, versioned_docs/version-2.21/reference/subsystems/scrooge.mdx, versioned_docs/version-2.21/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.21/reference/targets/pants_requirements.mdx, versioned_docs/version-2.21/reference/targets/python_requirement.mdx, versioned_docs/version-2.21/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.0
=> Update docs site for version 2.21.0

blog/2024-07-01-building-linux-on-osx-silicon/index.mdx, blog/authors.yml
Per @benjyw's request, I have written a blog post on getting linux/x64 builds working on osx/arm64 machines.
=> Blog Post: Building Linux/x64 containers on OS X on Apple Silicon with Pants

versioned_docs/version-2.22/docs/python/goals/repl.mdx, versioned_docs/version-2.22/docs/using-pants/environments.mdx, versioned_docs/version-2.22/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.22/reference/subsystems/jarjar.mdx, versioned_docs/version-2.22/reference/subsystems/java-avro.mdx, versioned_docs/version-2.22/reference/subsystems/junit.mdx, versioned_docs/version-2.22/reference/subsystems/ktlint.mdx, versioned_docs/version-2.22/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.22/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.22/reference/subsystems/scalafix.mdx, versioned_docs/version-2.22/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.22/reference/subsystems/scalapb.mdx, versioned_docs/version-2.22/reference/subsystems/scalatest.mdx, versioned_docs/version-2.22/reference/subsystems/scrooge.mdx, versioned_docs/version-2.22/reference/targets/experimental_workspace_environment.mdx, versioned_docs/version-2.22/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.22/reference/targets/pants_requirements.mdx, versioned_docs/version-2.22/reference/targets/python_requirement.mdx, versioned_docs/version-2.22/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.22.0rc0
=> Update docs site for version 2.22.0rc0

versioned_docs/version-2.22/reference/goals/export.mdx, versioned_docs/version-2.22/reference/subsystems/coverage-py.mdx, versioned_docs/version-2.22/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.22/reference/subsystems/jarjar.mdx, versioned_docs/version-2.22/reference/subsystems/java-avro.mdx, versioned_docs/version-2.22/reference/subsystems/junit.mdx, versioned_docs/version-2.22/reference/subsystems/ktlint.mdx, versioned_docs/version-2.22/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.22/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.22/reference/subsystems/scalafix.mdx, versioned_docs/version-2.22/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.22/reference/subsystems/scalapb.mdx, versioned_docs/version-2.22/reference/subsystems/scalatest.mdx, versioned_docs/version-2.22/reference/subsystems/scrooge.mdx, versioned_docs/version-2.22/reference/targets/experimental_workspace_environment.mdx, versioned_docs/version-2.22/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.22/reference/targets/pants_requirements.mdx, versioned_docs/version-2.22/reference/targets/python_requirement.mdx, versioned_docs/version-2.22/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.22.0rc2
=> Update docs site for version 2.22.0rc2

versioned_docs/version-2.20/docs/python/goals/repl.mdx, versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.3rc1
=> Update docs site for version 2.20.3rc1

versioned_docs/version-2.21/docs/python/goals/repl.mdx, versioned_docs/version-2.21/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.21/reference/subsystems/jarjar.mdx, versioned_docs/version-2.21/reference/subsystems/java-avro.mdx, versioned_docs/version-2.21/reference/subsystems/junit.mdx, versioned_docs/version-2.21/reference/subsystems/ktlint.mdx, versioned_docs/version-2.21/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.21/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.21/reference/subsystems/scalafix.mdx, versioned_docs/version-2.21/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.21/reference/subsystems/scalapb.mdx, versioned_docs/version-2.21/reference/subsystems/scalatest.mdx, versioned_docs/version-2.21/reference/subsystems/scrooge.mdx, versioned_docs/version-2.21/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.21/reference/targets/pants_requirements.mdx, versioned_docs/version-2.21/reference/targets/python_requirement.mdx, versioned_docs/version-2.21/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.1rc1
=> Update docs site for version 2.21.1rc1

versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.3
=> Update docs site for version 2.20.3

versioned_docs/version-2.21/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.21/reference/subsystems/jarjar.mdx, versioned_docs/version-2.21/reference/subsystems/java-avro.mdx, versioned_docs/version-2.21/reference/subsystems/junit.mdx, versioned_docs/version-2.21/reference/subsystems/ktlint.mdx, versioned_docs/version-2.21/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.21/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.21/reference/subsystems/scalafix.mdx, versioned_docs/version-2.21/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.21/reference/subsystems/scalapb.mdx, versioned_docs/version-2.21/reference/subsystems/scalatest.mdx, versioned_docs/version-2.21/reference/subsystems/scrooge.mdx, versioned_docs/version-2.21/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.21/reference/targets/pants_requirements.mdx, versioned_docs/version-2.21/reference/targets/python_requirement.mdx, versioned_docs/version-2.21/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.1
=> Update docs site for version 2.21.1

versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.4rc0
=> Update docs site for version 2.20.4rc0

versioned_docs/version-2.21/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.21/reference/subsystems/jarjar.mdx, versioned_docs/version-2.21/reference/subsystems/java-avro.mdx, versioned_docs/version-2.21/reference/subsystems/junit.mdx, versioned_docs/version-2.21/reference/subsystems/ktlint.mdx, versioned_docs/version-2.21/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.21/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.21/reference/subsystems/scalafix.mdx, versioned_docs/version-2.21/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.21/reference/subsystems/scalapb.mdx, versioned_docs/version-2.21/reference/subsystems/scalatest.mdx, versioned_docs/version-2.21/reference/subsystems/scrooge.mdx, versioned_docs/version-2.21/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.21/reference/targets/pants_requirements.mdx, versioned_docs/version-2.21/reference/targets/python_requirement.mdx, versioned_docs/version-2.21/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.2rc0
=> Update docs site for version 2.21.2rc0

versioned_docs/version-2.20/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.20/reference/subsystems/jarjar.mdx, versioned_docs/version-2.20/reference/subsystems/java-avro.mdx, versioned_docs/version-2.20/reference/subsystems/junit.mdx, versioned_docs/version-2.20/reference/subsystems/ktlint.mdx, versioned_docs/version-2.20/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.20/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.20/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.20/reference/subsystems/scalapb.mdx, versioned_docs/version-2.20/reference/subsystems/scalatest.mdx, versioned_docs/version-2.20/reference/subsystems/scrooge.mdx, versioned_docs/version-2.20/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.20/reference/targets/pants_requirements.mdx, versioned_docs/version-2.20/reference/targets/python_requirement.mdx, versioned_docs/version-2.20/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.20.4
=> Update docs site for version 2.20.4

blog/authors.yml
=> update cburroughs(me!) status in blog authors

blog/2023-02-23-the-pants-launcher-binary-a-much-simpler-way-to-install-and-run-pants/index.mdx
=> fix markdown footnote syntax in blog

versioned_docs/version-2.21/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.21/reference/subsystems/jarjar.mdx, versioned_docs/version-2.21/reference/subsystems/java-avro.mdx, versioned_docs/version-2.21/reference/subsystems/junit.mdx, versioned_docs/version-2.21/reference/subsystems/ktlint.mdx, versioned_docs/version-2.21/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.21/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.21/reference/subsystems/scalafix.mdx, versioned_docs/version-2.21/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.21/reference/subsystems/scalapb.mdx, versioned_docs/version-2.21/reference/subsystems/scalatest.mdx, versioned_docs/version-2.21/reference/subsystems/scrooge.mdx, versioned_docs/version-2.21/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.21/reference/targets/pants_requirements.mdx, versioned_docs/version-2.21/reference/targets/python_requirement.mdx, versioned_docs/version-2.21/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.2rc1
=> Update docs site for version 2.21.2rc1

src/pages/spotlight/service-providers.mdx
Add Shoal Software LLC (my personal consulting entity) as a Pants service provider.
=> add Shoal Software LLC as service provider

src/pages/spotlight/service-providers.mdx
=> fix typo in service providers page

versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.23/reference/subsystems/jarjar.mdx, versioned_docs/version-2.23/reference/subsystems/java-avro.mdx, versioned_docs/version-2.23/reference/subsystems/java-parser.mdx, versioned_docs/version-2.23/reference/subsystems/junit.mdx, versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.23/reference/subsystems/ktlint.mdx, versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.23/reference/subsystems/scalafix.mdx, versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.23/reference/subsystems/scalapb.mdx, versioned_docs/version-2.23/reference/subsystems/scalatest.mdx, versioned_docs/version-2.23/reference/subsystems/scrooge.mdx, versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.23/reference/targets/pants_requirements.mdx, versioned_docs/version-2.23/reference/targets/python_requirement.mdx, versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.0a1
=> Update docs site for version 2.23.0a1

blog/2024-09-10-pants-2-22/index.mdx, blog/2024-10-07-user-survey-2024/index.mdx, blog/2024-10-08-user-survey-2024/index.mdx, blog/authors.yml
Add blog post to announce the 2024 Pantsbuild User Survey.
=> add blog post to announce the 2024 Pantsbuild User Survey

versioned_docs/version-2.22/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.22/reference/subsystems/jarjar.mdx, versioned_docs/version-2.22/reference/subsystems/java-avro.mdx, versioned_docs/version-2.22/reference/subsystems/junit.mdx, versioned_docs/version-2.22/reference/subsystems/ktlint.mdx, versioned_docs/version-2.22/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.22/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.22/reference/subsystems/scalafix.mdx, versioned_docs/version-2.22/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.22/reference/subsystems/scalapb.mdx, versioned_docs/version-2.22/reference/subsystems/scalatest.mdx, versioned_docs/version-2.22/reference/subsystems/scrooge.mdx, versioned_docs/version-2.22/reference/subsystems/terraform-hcl2-parser.mdx, versioned_docs/version-2.22/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.22/reference/targets/pants_requirements.mdx, versioned_docs/version-2.22/reference/targets/python_requirement.mdx, versioned_docs/version-2.22/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.22.1rc1
=> Update docs site for version 2.22.1rc1

versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.23/reference/subsystems/jarjar.mdx, versioned_docs/version-2.23/reference/subsystems/java-avro.mdx, versioned_docs/version-2.23/reference/subsystems/java-parser.mdx, versioned_docs/version-2.23/reference/subsystems/junit.mdx, versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.23/reference/subsystems/ktlint.mdx, versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.23/reference/subsystems/scalafix.mdx, versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.23/reference/subsystems/scalapb.mdx, versioned_docs/version-2.23/reference/subsystems/scalatest.mdx, versioned_docs/version-2.23/reference/subsystems/scrooge.mdx, versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.23/reference/targets/pants_requirements.mdx, versioned_docs/version-2.23/reference/targets/python_requirement.mdx, versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.0rc0
=> Update docs site for version 2.23.0rc0

versioned_docs/version-2.22/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.22/reference/subsystems/jarjar.mdx, versioned_docs/version-2.22/reference/subsystems/java-avro.mdx, versioned_docs/version-2.22/reference/subsystems/junit.mdx, versioned_docs/version-2.22/reference/subsystems/ktlint.mdx, versioned_docs/version-2.22/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.22/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.22/reference/subsystems/scalafix.mdx, versioned_docs/version-2.22/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.22/reference/subsystems/scalapb.mdx, versioned_docs/version-2.22/reference/subsystems/scalatest.mdx, versioned_docs/version-2.22/reference/subsystems/scrooge.mdx, versioned_docs/version-2.22/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.22/reference/targets/pants_requirements.mdx, versioned_docs/version-2.22/reference/targets/python_requirement.mdx, versioned_docs/version-2.22/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.22.1rc2
=> Update docs site for version 2.22.1rc2

versioned_docs/version-2.21/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.21/reference/subsystems/jarjar.mdx, versioned_docs/version-2.21/reference/subsystems/java-avro.mdx, versioned_docs/version-2.21/reference/subsystems/junit.mdx, versioned_docs/version-2.21/reference/subsystems/ktlint.mdx, versioned_docs/version-2.21/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.21/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.21/reference/subsystems/scalafix.mdx, versioned_docs/version-2.21/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.21/reference/subsystems/scalapb.mdx, versioned_docs/version-2.21/reference/subsystems/scalatest.mdx, versioned_docs/version-2.21/reference/subsystems/scrooge.mdx, versioned_docs/version-2.21/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.21/reference/targets/pants_requirements.mdx, versioned_docs/version-2.21/reference/targets/python_requirement.mdx, versioned_docs/version-2.21/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.2rc2
=> Update docs site for version 2.21.2rc2

src/pages/community/meet-the-team.mdx
Originally added in https://github.com/pantsbuild/pants/pull/20329 but somehow got dropped out on this end of things.
=> Re-add Krishnan Chandra to contributors

versioned_docs/version-2.22/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.22/reference/subsystems/jarjar.mdx, versioned_docs/version-2.22/reference/subsystems/java-avro.mdx, versioned_docs/version-2.22/reference/subsystems/junit.mdx, versioned_docs/version-2.22/reference/subsystems/ktlint.mdx, versioned_docs/version-2.22/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.22/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.22/reference/subsystems/scalafix.mdx, versioned_docs/version-2.22/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.22/reference/subsystems/scalapb.mdx, versioned_docs/version-2.22/reference/subsystems/scalatest.mdx, versioned_docs/version-2.22/reference/subsystems/scrooge.mdx, versioned_docs/version-2.22/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.22/reference/targets/pants_requirements.mdx, versioned_docs/version-2.22/reference/targets/python_requirement.mdx, versioned_docs/version-2.22/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.22.1rc3
=> Update docs site for version 2.22.1rc3

versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.23/reference/subsystems/jarjar.mdx, versioned_docs/version-2.23/reference/subsystems/java-avro.mdx, versioned_docs/version-2.23/reference/subsystems/java-parser.mdx, versioned_docs/version-2.23/reference/subsystems/junit.mdx, versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.23/reference/subsystems/ktlint.mdx, versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.23/reference/subsystems/scalafix.mdx, versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.23/reference/subsystems/scalapb.mdx, versioned_docs/version-2.23/reference/subsystems/scalatest.mdx, versioned_docs/version-2.23/reference/subsystems/scrooge.mdx, versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.23/reference/targets/pants_requirements.mdx, versioned_docs/version-2.23/reference/targets/python_requirement.mdx, versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.0rc2
=> Update docs site for version 2.23.0rc2

versioned_docs/version-2.21/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.21/reference/subsystems/jarjar.mdx, versioned_docs/version-2.21/reference/subsystems/java-avro.mdx, versioned_docs/version-2.21/reference/subsystems/junit.mdx, versioned_docs/version-2.21/reference/subsystems/ktlint.mdx, versioned_docs/version-2.21/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.21/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.21/reference/subsystems/scalafix.mdx, versioned_docs/version-2.21/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.21/reference/subsystems/scalapb.mdx, versioned_docs/version-2.21/reference/subsystems/scalatest.mdx, versioned_docs/version-2.21/reference/subsystems/scrooge.mdx, versioned_docs/version-2.21/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.21/reference/targets/pants_requirements.mdx, versioned_docs/version-2.21/reference/targets/python_requirement.mdx, versioned_docs/version-2.21/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.2
=> Update docs site for version 2.21.2

versioned_docs/version-2.22/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.22/reference/subsystems/jarjar.mdx, versioned_docs/version-2.22/reference/subsystems/java-avro.mdx, versioned_docs/version-2.22/reference/subsystems/junit.mdx, versioned_docs/version-2.22/reference/subsystems/ktlint.mdx, versioned_docs/version-2.22/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.22/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.22/reference/subsystems/scalafix.mdx, versioned_docs/version-2.22/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.22/reference/subsystems/scalapb.mdx, versioned_docs/version-2.22/reference/subsystems/scalatest.mdx, versioned_docs/version-2.22/reference/subsystems/scrooge.mdx, versioned_docs/version-2.22/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.22/reference/targets/pants_requirements.mdx, versioned_docs/version-2.22/reference/targets/python_requirement.mdx, versioned_docs/version-2.22/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.22.1
=> Update docs site for version 2.22.1

versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.23/reference/subsystems/jarjar.mdx, versioned_docs/version-2.23/reference/subsystems/java-avro.mdx, versioned_docs/version-2.23/reference/subsystems/java-parser.mdx, versioned_docs/version-2.23/reference/subsystems/junit.mdx, versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.23/reference/subsystems/ktlint.mdx, versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.23/reference/subsystems/scalafix.mdx, versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.23/reference/subsystems/scalapb.mdx, versioned_docs/version-2.23/reference/subsystems/scalatest.mdx, versioned_docs/version-2.23/reference/subsystems/scrooge.mdx, versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.23/reference/targets/pants_requirements.mdx, versioned_docs/version-2.23/reference/targets/python_requirement.mdx, versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.0rc3
=> Update docs site for version 2.23.0rc3

versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.23/reference/subsystems/jarjar.mdx, versioned_docs/version-2.23/reference/subsystems/java-avro.mdx, versioned_docs/version-2.23/reference/subsystems/java-parser.mdx, versioned_docs/version-2.23/reference/subsystems/junit.mdx, versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.23/reference/subsystems/ktlint.mdx, versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.23/reference/subsystems/scalafix.mdx, versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.23/reference/subsystems/scalapb.mdx, versioned_docs/version-2.23/reference/subsystems/scalatest.mdx, versioned_docs/version-2.23/reference/subsystems/scrooge.mdx, versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.23/reference/targets/pants_requirements.mdx, versioned_docs/version-2.23/reference/targets/python_requirement.mdx, versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.0
=> Update docs site for version 2.23.0

versioned_docs/version-2.24/docs/getting-started/installing-pants.mdx, versioned_docs/version-2.24/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.24/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.24/reference/subsystems/jarjar.mdx, versioned_docs/version-2.24/reference/subsystems/java-avro.mdx, versioned_docs/version-2.24/reference/subsystems/java-parser.mdx, versioned_docs/version-2.24/reference/subsystems/junit.mdx, versioned_docs/version-2.24/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.24/reference/subsystems/ktlint.mdx, versioned_docs/version-2.24/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.24/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.24/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.24/reference/subsystems/scalafix.mdx, versioned_docs/version-2.24/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.24/reference/subsystems/scalapb.mdx, versioned_docs/version-2.24/reference/subsystems/scalatest.mdx, versioned_docs/version-2.24/reference/subsystems/scrooge.mdx, versioned_docs/version-2.24/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.24/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.24/reference/targets/pants_requirements.mdx, versioned_docs/version-2.24/reference/targets/python_requirement.mdx, versioned_docs/version-2.24/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.24.0rc0
=> Update docs site for version 2.24.0rc0

docs/docs/contributions/development/setting-up-pants.mdx, docs/reference/subsystems/google-java-format.mdx, docs/reference/subsystems/jar_tool.mdx, docs/reference/subsystems/jarjar.mdx, docs/reference/subsystems/java-avro.mdx, docs/reference/subsystems/java-parser.mdx, docs/reference/subsystems/junit.mdx, docs/reference/subsystems/kotlin-parser.mdx, docs/reference/subsystems/ktlint.mdx, docs/reference/subsystems/openapi-generator.mdx, docs/reference/subsystems/pex-cli.mdx, docs/reference/subsystems/protobuf-java-grpc.mdx, docs/reference/subsystems/python-build-standalone-python-provider.mdx, docs/reference/subsystems/scala-parser.mdx, docs/reference/subsystems/scalafix.mdx, docs/reference/subsystems/scalafmt.mdx, docs/reference/subsystems/scalapb.mdx, docs/reference/subsystems/scalatest.mdx, docs/reference/subsystems/scrooge.mdx, docs/reference/subsystems/strip-jar.mdx, docs/reference/targets/jvm_artifact.mdx, docs/reference/targets/pants_requirements.mdx, docs/reference/targets/python_requirement.mdx, docs/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.25.0.dev2
=> Update docs site for version 2.25.0.dev2

versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.23/reference/subsystems/jarjar.mdx, versioned_docs/version-2.23/reference/subsystems/java-avro.mdx, versioned_docs/version-2.23/reference/subsystems/java-parser.mdx, versioned_docs/version-2.23/reference/subsystems/junit.mdx, versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.23/reference/subsystems/ktlint.mdx, versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.23/reference/subsystems/scalafix.mdx, versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.23/reference/subsystems/scalapb.mdx, versioned_docs/version-2.23/reference/subsystems/scalatest.mdx, versioned_docs/version-2.23/reference/subsystems/scrooge.mdx, versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.23/reference/targets/pants_requirements.mdx, versioned_docs/version-2.23/reference/targets/python_requirement.mdx, versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.1
=> Update docs site for version 2.23.1

versioned_docs/version-2.24/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.24/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.24/reference/subsystems/jarjar.mdx, versioned_docs/version-2.24/reference/subsystems/java-avro.mdx, versioned_docs/version-2.24/reference/subsystems/java-parser.mdx, versioned_docs/version-2.24/reference/subsystems/junit.mdx, versioned_docs/version-2.24/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.24/reference/subsystems/ktlint.mdx, versioned_docs/version-2.24/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.24/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.24/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.24/reference/subsystems/scalafix.mdx, versioned_docs/version-2.24/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.24/reference/subsystems/scalapb.mdx, versioned_docs/version-2.24/reference/subsystems/scalatest.mdx, versioned_docs/version-2.24/reference/subsystems/scrooge.mdx, versioned_docs/version-2.24/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.24/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.24/reference/targets/pants_requirements.mdx, versioned_docs/version-2.24/reference/targets/python_requirement.mdx, versioned_docs/version-2.24/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.24.0rc3
=> Update docs site for version 2.24.0rc3

versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.23/reference/subsystems/jarjar.mdx, versioned_docs/version-2.23/reference/subsystems/java-avro.mdx, versioned_docs/version-2.23/reference/subsystems/java-parser.mdx, versioned_docs/version-2.23/reference/subsystems/junit.mdx, versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.23/reference/subsystems/ktlint.mdx, versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.23/reference/subsystems/scalafix.mdx, versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.23/reference/subsystems/scalapb.mdx, versioned_docs/version-2.23/reference/subsystems/scalatest.mdx, versioned_docs/version-2.23/reference/subsystems/scrooge.mdx, versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.23/reference/targets/pants_requirements.mdx, versioned_docs/version-2.23/reference/targets/python_requirement.mdx, versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.2rc0
=> Update docs site for version 2.23.2rc0

versioned_docs/version-2.24/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.24/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.24/reference/subsystems/jarjar.mdx, versioned_docs/version-2.24/reference/subsystems/java-avro.mdx, versioned_docs/version-2.24/reference/subsystems/java-parser.mdx, versioned_docs/version-2.24/reference/subsystems/junit.mdx, versioned_docs/version-2.24/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.24/reference/subsystems/ktlint.mdx, versioned_docs/version-2.24/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.24/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.24/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.24/reference/subsystems/scalafix.mdx, versioned_docs/version-2.24/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.24/reference/subsystems/scalapb.mdx, versioned_docs/version-2.24/reference/subsystems/scalatest.mdx, versioned_docs/version-2.24/reference/subsystems/scrooge.mdx, versioned_docs/version-2.24/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.24/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.24/reference/targets/pants_requirements.mdx, versioned_docs/version-2.24/reference/targets/python_requirement.mdx, versioned_docs/version-2.24/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.24.0
=> Update docs site for version 2.24.0

versioned_docs/version-2.23/docs/contributions/releases/index.mdx, versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.23/reference/subsystems/jarjar.mdx, versioned_docs/version-2.23/reference/subsystems/java-avro.mdx, versioned_docs/version-2.23/reference/subsystems/java-parser.mdx, versioned_docs/version-2.23/reference/subsystems/junit.mdx, versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.23/reference/subsystems/ktlint.mdx, versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.23/reference/subsystems/scalafix.mdx, versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.23/reference/subsystems/scalapb.mdx, versioned_docs/version-2.23/reference/subsystems/scalatest.mdx, versioned_docs/version-2.23/reference/subsystems/scrooge.mdx, versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.23/reference/targets/pants_requirements.mdx, versioned_docs/version-2.23/reference/targets/python_requirement.mdx, versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.2rc1
=> Update docs site for version 2.23.2rc1

versioned_docs/version-2.24/docs/contributions/releases/index.mdx, versioned_docs/version-2.24/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.24/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.24/reference/subsystems/jarjar.mdx, versioned_docs/version-2.24/reference/subsystems/java-avro.mdx, versioned_docs/version-2.24/reference/subsystems/java-parser.mdx, versioned_docs/version-2.24/reference/subsystems/junit.mdx, versioned_docs/version-2.24/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.24/reference/subsystems/ktlint.mdx, versioned_docs/version-2.24/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.24/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.24/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.24/reference/subsystems/scalafix.mdx, versioned_docs/version-2.24/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.24/reference/subsystems/scalapb.mdx, versioned_docs/version-2.24/reference/subsystems/scalatest.mdx, versioned_docs/version-2.24/reference/subsystems/scrooge.mdx, versioned_docs/version-2.24/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.24/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.24/reference/targets/pants_requirements.mdx, versioned_docs/version-2.24/reference/targets/python_requirement.mdx, versioned_docs/version-2.24/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.24.1rc0
=> Update docs site for version 2.24.1rc0

versioned_docs/version-2.23/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.23/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.23/reference/subsystems/jarjar.mdx, versioned_docs/version-2.23/reference/subsystems/java-avro.mdx, versioned_docs/version-2.23/reference/subsystems/java-parser.mdx, versioned_docs/version-2.23/reference/subsystems/junit.mdx, versioned_docs/version-2.23/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.23/reference/subsystems/ktlint.mdx, versioned_docs/version-2.23/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.23/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.23/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.23/reference/subsystems/scalafix.mdx, versioned_docs/version-2.23/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.23/reference/subsystems/scalapb.mdx, versioned_docs/version-2.23/reference/subsystems/scalatest.mdx, versioned_docs/version-2.23/reference/subsystems/scrooge.mdx, versioned_docs/version-2.23/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.23/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.23/reference/targets/pants_requirements.mdx, versioned_docs/version-2.23/reference/targets/python_requirement.mdx, versioned_docs/version-2.23/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.23.2
=> Update docs site for version 2.23.2

versioned_docs/version-2.24/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.24/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.24/reference/subsystems/jarjar.mdx, versioned_docs/version-2.24/reference/subsystems/java-avro.mdx, versioned_docs/version-2.24/reference/subsystems/java-parser.mdx, versioned_docs/version-2.24/reference/subsystems/junit.mdx, versioned_docs/version-2.24/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.24/reference/subsystems/ktlint.mdx, versioned_docs/version-2.24/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.24/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.24/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.24/reference/subsystems/scalafix.mdx, versioned_docs/version-2.24/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.24/reference/subsystems/scalapb.mdx, versioned_docs/version-2.24/reference/subsystems/scalatest.mdx, versioned_docs/version-2.24/reference/subsystems/scrooge.mdx, versioned_docs/version-2.24/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.24/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.24/reference/targets/pants_requirements.mdx, versioned_docs/version-2.24/reference/targets/python_requirement.mdx, versioned_docs/version-2.24/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.24.1
=> Update docs site for version 2.24.1

versioned_docs/version-2.24/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.24/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.24/reference/subsystems/jarjar.mdx, versioned_docs/version-2.24/reference/subsystems/java-avro.mdx, versioned_docs/version-2.24/reference/subsystems/java-parser.mdx, versioned_docs/version-2.24/reference/subsystems/junit.mdx, versioned_docs/version-2.24/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.24/reference/subsystems/ktlint.mdx, versioned_docs/version-2.24/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.24/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.24/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.24/reference/subsystems/scalafix.mdx, versioned_docs/version-2.24/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.24/reference/subsystems/scalapb.mdx, versioned_docs/version-2.24/reference/subsystems/scalatest.mdx, versioned_docs/version-2.24/reference/subsystems/scrooge.mdx, versioned_docs/version-2.24/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.24/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.24/reference/targets/pants_requirements.mdx, versioned_docs/version-2.24/reference/targets/python_requirement.mdx, versioned_docs/version-2.24/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.24.2
=> Update docs site for version 2.24.2

versioned_docs/version-2.25/docs/using-pants/project-introspection.mdx, versioned_docs/version-2.25/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.25/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.25/reference/subsystems/jarjar.mdx, versioned_docs/version-2.25/reference/subsystems/java-avro.mdx, versioned_docs/version-2.25/reference/subsystems/java-parser.mdx, versioned_docs/version-2.25/reference/subsystems/junit.mdx, versioned_docs/version-2.25/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.25/reference/subsystems/ktlint.mdx, versioned_docs/version-2.25/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.25/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.25/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.25/reference/subsystems/scalafix.mdx, versioned_docs/version-2.25/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.25/reference/subsystems/scalapb.mdx, versioned_docs/version-2.25/reference/subsystems/scalatest.mdx, versioned_docs/version-2.25/reference/subsystems/scrooge.mdx, versioned_docs/version-2.25/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.25/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.25/reference/targets/pants_requirements.mdx, versioned_docs/version-2.25/reference/targets/python_requirement.mdx, versioned_docs/version-2.25/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.25.0rc1
=> Update docs site for version 2.25.0rc1

versioned_docs/version-2.24/docs/using-pants/project-introspection.mdx, versioned_docs/version-2.24/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.24/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.24/reference/subsystems/jarjar.mdx, versioned_docs/version-2.24/reference/subsystems/java-avro.mdx, versioned_docs/version-2.24/reference/subsystems/java-parser.mdx, versioned_docs/version-2.24/reference/subsystems/junit.mdx, versioned_docs/version-2.24/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.24/reference/subsystems/ktlint.mdx, versioned_docs/version-2.24/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.24/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.24/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.24/reference/subsystems/scalafix.mdx, versioned_docs/version-2.24/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.24/reference/subsystems/scalapb.mdx, versioned_docs/version-2.24/reference/subsystems/scalatest.mdx, versioned_docs/version-2.24/reference/subsystems/scrooge.mdx, versioned_docs/version-2.24/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.24/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.24/reference/targets/pants_requirements.mdx, versioned_docs/version-2.24/reference/targets/python_requirement.mdx, versioned_docs/version-2.24/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.24.3rc0
=> Update docs site for version 2.24.3rc0

versioned_docs/version-2.25/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.25/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.25/reference/subsystems/jarjar.mdx, versioned_docs/version-2.25/reference/subsystems/java-avro.mdx, versioned_docs/version-2.25/reference/subsystems/java-parser.mdx, versioned_docs/version-2.25/reference/subsystems/junit.mdx, versioned_docs/version-2.25/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.25/reference/subsystems/ktlint.mdx, versioned_docs/version-2.25/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.25/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.25/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.25/reference/subsystems/scalafix.mdx, versioned_docs/version-2.25/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.25/reference/subsystems/scalapb.mdx, versioned_docs/version-2.25/reference/subsystems/scalatest.mdx, versioned_docs/version-2.25/reference/subsystems/scrooge.mdx, versioned_docs/version-2.25/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.25/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.25/reference/targets/pants_requirements.mdx, versioned_docs/version-2.25/reference/targets/python_requirement.mdx, versioned_docs/version-2.25/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.25.0
=> Update docs site for version 2.25.0

versioned_docs/version-2.26/docs/contributions/development/setting-up-pants.mdx, versioned_docs/version-2.26/docs/writing-plugins/overview.mdx, versioned_docs/version-2.26/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.26/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.26/reference/subsystems/jarjar.mdx, versioned_docs/version-2.26/reference/subsystems/java-avro.mdx, versioned_docs/version-2.26/reference/subsystems/java-parser.mdx, versioned_docs/version-2.26/reference/subsystems/junit.mdx, versioned_docs/version-2.26/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.26/reference/subsystems/ktlint.mdx, versioned_docs/version-2.26/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.26/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.26/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.26/reference/subsystems/scalafix.mdx, versioned_docs/version-2.26/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.26/reference/subsystems/scalapb.mdx, versioned_docs/version-2.26/reference/subsystems/scalatest.mdx, versioned_docs/version-2.26/reference/subsystems/scrooge.mdx, versioned_docs/version-2.26/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.26/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.26/reference/targets/pants_requirements.mdx, versioned_docs/version-2.26/reference/targets/python_requirement.mdx, versioned_docs/version-2.26/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.26.0a1
=> Update docs site for version 2.26.0a1

versioned_docs/version-2.24/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.24/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.24/reference/subsystems/jarjar.mdx, versioned_docs/version-2.24/reference/subsystems/java-avro.mdx, versioned_docs/version-2.24/reference/subsystems/java-parser.mdx, versioned_docs/version-2.24/reference/subsystems/junit.mdx, versioned_docs/version-2.24/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.24/reference/subsystems/ktlint.mdx, versioned_docs/version-2.24/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.24/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.24/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.24/reference/subsystems/scalafix.mdx, versioned_docs/version-2.24/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.24/reference/subsystems/scalapb.mdx, versioned_docs/version-2.24/reference/subsystems/scalatest.mdx, versioned_docs/version-2.24/reference/subsystems/scrooge.mdx, versioned_docs/version-2.24/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.24/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.24/reference/targets/pants_requirements.mdx, versioned_docs/version-2.24/reference/targets/python_requirement.mdx, versioned_docs/version-2.24/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.24.3rc1
=> Update docs site for version 2.24.3rc1

versioned_docs/version-2.25/docs/contributions/development/setting-up-pants.mdx, versioned_docs/version-2.25/docs/writing-plugins/overview.mdx, versioned_docs/version-2.25/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.25/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.25/reference/subsystems/jarjar.mdx, versioned_docs/version-2.25/reference/subsystems/java-avro.mdx, versioned_docs/version-2.25/reference/subsystems/java-parser.mdx, versioned_docs/version-2.25/reference/subsystems/junit.mdx, versioned_docs/version-2.25/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.25/reference/subsystems/ktlint.mdx, versioned_docs/version-2.25/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.25/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.25/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.25/reference/subsystems/scalafix.mdx, versioned_docs/version-2.25/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.25/reference/subsystems/scalapb.mdx, versioned_docs/version-2.25/reference/subsystems/scalatest.mdx, versioned_docs/version-2.25/reference/subsystems/scrooge.mdx, versioned_docs/version-2.25/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.25/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.25/reference/targets/pants_requirements.mdx, versioned_docs/version-2.25/reference/targets/python_requirement.mdx, versioned_docs/version-2.25/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.25.1rc0
=> Update docs site for version 2.25.1rc0

versioned_docs/version-2.24/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.24/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.24/reference/subsystems/jarjar.mdx, versioned_docs/version-2.24/reference/subsystems/java-avro.mdx, versioned_docs/version-2.24/reference/subsystems/java-parser.mdx, versioned_docs/version-2.24/reference/subsystems/junit.mdx, versioned_docs/version-2.24/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.24/reference/subsystems/ktlint.mdx, versioned_docs/version-2.24/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.24/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.24/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.24/reference/subsystems/scalafix.mdx, versioned_docs/version-2.24/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.24/reference/subsystems/scalapb.mdx, versioned_docs/version-2.24/reference/subsystems/scalatest.mdx, versioned_docs/version-2.24/reference/subsystems/scrooge.mdx, versioned_docs/version-2.24/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.24/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.24/reference/targets/pants_requirements.mdx, versioned_docs/version-2.24/reference/targets/python_requirement.mdx, versioned_docs/version-2.24/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.24.3
=> Update docs site for version 2.24.3

versioned_docs/version-2.25/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.25/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.25/reference/subsystems/jarjar.mdx, versioned_docs/version-2.25/reference/subsystems/java-avro.mdx, versioned_docs/version-2.25/reference/subsystems/java-parser.mdx, versioned_docs/version-2.25/reference/subsystems/junit.mdx, versioned_docs/version-2.25/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.25/reference/subsystems/ktlint.mdx, versioned_docs/version-2.25/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.25/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.25/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.25/reference/subsystems/scalafix.mdx, versioned_docs/version-2.25/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.25/reference/subsystems/scalapb.mdx, versioned_docs/version-2.25/reference/subsystems/scalatest.mdx, versioned_docs/version-2.25/reference/subsystems/scrooge.mdx, versioned_docs/version-2.25/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.25/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.25/reference/targets/pants_requirements.mdx, versioned_docs/version-2.25/reference/targets/python_requirement.mdx, versioned_docs/version-2.25/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.25.1
=> Update docs site for version 2.25.1

versioned_docs/version-2.26/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.26/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.26/reference/subsystems/jarjar.mdx, versioned_docs/version-2.26/reference/subsystems/java-avro.mdx, versioned_docs/version-2.26/reference/subsystems/java-parser.mdx, versioned_docs/version-2.26/reference/subsystems/junit.mdx, versioned_docs/version-2.26/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.26/reference/subsystems/ktlint.mdx, versioned_docs/version-2.26/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.26/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.26/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.26/reference/subsystems/scalafix.mdx, versioned_docs/version-2.26/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.26/reference/subsystems/scalapb.mdx, versioned_docs/version-2.26/reference/subsystems/scalatest.mdx, versioned_docs/version-2.26/reference/subsystems/scrooge.mdx, versioned_docs/version-2.26/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.26/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.26/reference/targets/pants_requirements.mdx, versioned_docs/version-2.26/reference/targets/python_requirement.mdx, versioned_docs/version-2.26/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.26.0rc0
=> Update docs site for version 2.26.0rc0

docs/reference/subsystems/google-java-format.mdx, docs/reference/subsystems/jar_tool.mdx, docs/reference/subsystems/jarjar.mdx, docs/reference/subsystems/java-avro.mdx, docs/reference/subsystems/java-parser.mdx, docs/reference/subsystems/junit.mdx, docs/reference/subsystems/kotlin-parser.mdx, docs/reference/subsystems/ktlint.mdx, docs/reference/subsystems/openapi-generator.mdx, docs/reference/subsystems/protobuf-java-grpc.mdx, docs/reference/subsystems/scala-parser.mdx, docs/reference/subsystems/scalafix.mdx, docs/reference/subsystems/scalafmt.mdx, docs/reference/subsystems/scalapb.mdx, docs/reference/subsystems/scalatest.mdx, docs/reference/subsystems/scrooge.mdx, docs/reference/subsystems/strip-jar.mdx, docs/reference/targets/jvm_artifact.mdx, docs/reference/targets/pants_requirements.mdx, docs/reference/targets/python_requirement.mdx, docs/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.27.0.dev2
=> Update docs site for version 2.27.0.dev2

versioned_docs/version-2.26/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.26/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.26/reference/subsystems/jarjar.mdx, versioned_docs/version-2.26/reference/subsystems/java-avro.mdx, versioned_docs/version-2.26/reference/subsystems/java-parser.mdx, versioned_docs/version-2.26/reference/subsystems/junit.mdx, versioned_docs/version-2.26/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.26/reference/subsystems/ktlint.mdx, versioned_docs/version-2.26/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.26/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.26/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.26/reference/subsystems/scalafix.mdx, versioned_docs/version-2.26/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.26/reference/subsystems/scalapb.mdx, versioned_docs/version-2.26/reference/subsystems/scalatest.mdx, versioned_docs/version-2.26/reference/subsystems/scrooge.mdx, versioned_docs/version-2.26/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.26/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.26/reference/targets/pants_requirements.mdx, versioned_docs/version-2.26/reference/targets/python_requirement.mdx, versioned_docs/version-2.26/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.26.0
=> Update docs site for version 2.26.0

docs/reference/subsystems/docker.mdx, docs/reference/subsystems/google-java-format.mdx, docs/reference/subsystems/jar_tool.mdx, docs/reference/subsystems/jarjar.mdx, docs/reference/subsystems/java-avro.mdx, docs/reference/subsystems/java-parser.mdx, docs/reference/subsystems/junit.mdx, docs/reference/subsystems/kotlin-parser.mdx, docs/reference/subsystems/ktlint.mdx, docs/reference/subsystems/openapi-generator.mdx, docs/reference/subsystems/protobuf-java-grpc.mdx, docs/reference/subsystems/scala-parser.mdx, docs/reference/subsystems/scalafix.mdx, docs/reference/subsystems/scalafmt.mdx, docs/reference/subsystems/scalapb.mdx, docs/reference/subsystems/scalatest.mdx, docs/reference/subsystems/scrooge.mdx, docs/reference/subsystems/strip-jar.mdx, docs/reference/targets/jvm_artifact.mdx, docs/reference/targets/pants_requirements.mdx, docs/reference/targets/python_requirement.mdx, docs/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.28.0.dev1
=> Update docs site for version 2.28.0.dev1

versioned_docs/version-2.27/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.27/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.27/reference/subsystems/jarjar.mdx, versioned_docs/version-2.27/reference/subsystems/java-avro.mdx, versioned_docs/version-2.27/reference/subsystems/java-parser.mdx, versioned_docs/version-2.27/reference/subsystems/junit.mdx, versioned_docs/version-2.27/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.27/reference/subsystems/ktlint.mdx, versioned_docs/version-2.27/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.27/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.27/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.27/reference/subsystems/scalafix.mdx, versioned_docs/version-2.27/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.27/reference/subsystems/scalapb.mdx, versioned_docs/version-2.27/reference/subsystems/scalatest.mdx, versioned_docs/version-2.27/reference/subsystems/scrooge.mdx, versioned_docs/version-2.27/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.27/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.27/reference/targets/pants_requirements.mdx, versioned_docs/version-2.27/reference/targets/python_requirement.mdx, versioned_docs/version-2.27/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.27.0rc0
=> Update docs site for version 2.27.0rc0

versioned_docs/version-2.26/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.26/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.26/reference/subsystems/jarjar.mdx, versioned_docs/version-2.26/reference/subsystems/java-avro.mdx, versioned_docs/version-2.26/reference/subsystems/java-parser.mdx, versioned_docs/version-2.26/reference/subsystems/junit.mdx, versioned_docs/version-2.26/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.26/reference/subsystems/ktlint.mdx, versioned_docs/version-2.26/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.26/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.26/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.26/reference/subsystems/scalafix.mdx, versioned_docs/version-2.26/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.26/reference/subsystems/scalapb.mdx, versioned_docs/version-2.26/reference/subsystems/scalatest.mdx, versioned_docs/version-2.26/reference/subsystems/scrooge.mdx, versioned_docs/version-2.26/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.26/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.26/reference/targets/pants_requirements.mdx, versioned_docs/version-2.26/reference/targets/python_requirement.mdx, versioned_docs/version-2.26/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.26.1rc0
=> Update docs site for version 2.26.1rc0

versioned_docs/version-2.25/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.25/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.25/reference/subsystems/jarjar.mdx, versioned_docs/version-2.25/reference/subsystems/java-avro.mdx, versioned_docs/version-2.25/reference/subsystems/java-parser.mdx, versioned_docs/version-2.25/reference/subsystems/junit.mdx, versioned_docs/version-2.25/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.25/reference/subsystems/ktlint.mdx, versioned_docs/version-2.25/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.25/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.25/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.25/reference/subsystems/scalafix.mdx, versioned_docs/version-2.25/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.25/reference/subsystems/scalapb.mdx, versioned_docs/version-2.25/reference/subsystems/scalatest.mdx, versioned_docs/version-2.25/reference/subsystems/scrooge.mdx, versioned_docs/version-2.25/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.25/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.25/reference/targets/pants_requirements.mdx, versioned_docs/version-2.25/reference/targets/python_requirement.mdx, versioned_docs/version-2.25/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.25.2rc0
=> Update docs site for version 2.25.2rc0

versioned_docs/version-2.25/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.25/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.25/reference/subsystems/jarjar.mdx, versioned_docs/version-2.25/reference/subsystems/java-avro.mdx, versioned_docs/version-2.25/reference/subsystems/java-parser.mdx, versioned_docs/version-2.25/reference/subsystems/junit.mdx, versioned_docs/version-2.25/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.25/reference/subsystems/ktlint.mdx, versioned_docs/version-2.25/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.25/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.25/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.25/reference/subsystems/scalafix.mdx, versioned_docs/version-2.25/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.25/reference/subsystems/scalapb.mdx, versioned_docs/version-2.25/reference/subsystems/scalatest.mdx, versioned_docs/version-2.25/reference/subsystems/scrooge.mdx, versioned_docs/version-2.25/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.25/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.25/reference/targets/pants_requirements.mdx, versioned_docs/version-2.25/reference/targets/python_requirement.mdx, versioned_docs/version-2.25/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.25.2
=> Update docs site for version 2.25.2

versioned_docs/version-2.25/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.25/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.25/reference/subsystems/jarjar.mdx, versioned_docs/version-2.25/reference/subsystems/java-avro.mdx, versioned_docs/version-2.25/reference/subsystems/java-parser.mdx, versioned_docs/version-2.25/reference/subsystems/junit.mdx, versioned_docs/version-2.25/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.25/reference/subsystems/ktlint.mdx, versioned_docs/version-2.25/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.25/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.25/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.25/reference/subsystems/scalafix.mdx, versioned_docs/version-2.25/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.25/reference/subsystems/scalapb.mdx, versioned_docs/version-2.25/reference/subsystems/scalatest.mdx, versioned_docs/version-2.25/reference/subsystems/scrooge.mdx, versioned_docs/version-2.25/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.25/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.25/reference/targets/openapi_document.mdx, versioned_docs/version-2.25/reference/targets/openapi_documents.mdx, versioned_docs/version-2.25/reference/targets/pants_requirements.mdx, versioned_docs/version-2.25/reference/targets/python_requirement.mdx, versioned_docs/version-2.25/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.25.3rc0
=> Update docs site for version 2.25.3rc0

versioned_docs/version-2.25/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.25/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.25/reference/subsystems/jarjar.mdx, versioned_docs/version-2.25/reference/subsystems/java-avro.mdx, versioned_docs/version-2.25/reference/subsystems/java-parser.mdx, versioned_docs/version-2.25/reference/subsystems/junit.mdx, versioned_docs/version-2.25/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.25/reference/subsystems/ktlint.mdx, versioned_docs/version-2.25/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.25/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.25/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.25/reference/subsystems/scalafix.mdx, versioned_docs/version-2.25/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.25/reference/subsystems/scalapb.mdx, versioned_docs/version-2.25/reference/subsystems/scalatest.mdx, versioned_docs/version-2.25/reference/subsystems/scrooge.mdx, versioned_docs/version-2.25/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.25/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.25/reference/targets/pants_requirements.mdx, versioned_docs/version-2.25/reference/targets/python_requirement.mdx, versioned_docs/version-2.25/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.25.3
=> Update docs site for version 2.25.3

versioned_docs/version-2.26/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.26/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.26/reference/subsystems/jarjar.mdx, versioned_docs/version-2.26/reference/subsystems/java-avro.mdx, versioned_docs/version-2.26/reference/subsystems/java-parser.mdx, versioned_docs/version-2.26/reference/subsystems/junit.mdx, versioned_docs/version-2.26/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.26/reference/subsystems/ktlint.mdx, versioned_docs/version-2.26/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.26/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.26/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.26/reference/subsystems/scalafix.mdx, versioned_docs/version-2.26/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.26/reference/subsystems/scalapb.mdx, versioned_docs/version-2.26/reference/subsystems/scalatest.mdx, versioned_docs/version-2.26/reference/subsystems/scrooge.mdx, versioned_docs/version-2.26/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.26/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.26/reference/targets/pants_requirements.mdx, versioned_docs/version-2.26/reference/targets/python_requirement.mdx, versioned_docs/version-2.26/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.26.2
=> Update docs site for version 2.26.2

README.md, blog/2021-11-18-pants-vs-bazel/index.mdx, package.json, pnpm-lock.yaml
=> Updated the readme for `pnpm` instead of `yarn`/`npm`

src/pages/community/maintainers.mdx, src/pages/community/meet-the-team.mdx
Also fix a bad link in the maintainers page. 
The old link spanned an entire sentence, and
pointed back to the same page.
=> Add Nick Dell'Osa to the Contributors list.

blog/2021-11-18-pants-vs-bazel/index.mdx, src/pages/community/meet-the-team.mdx
Also move Nick Dell'Osa to the correct table.
=> Add Gregory Borodin to Contributors.

docs/reference/subsystems/google-java-format.mdx, docs/reference/subsystems/jar_tool.mdx, docs/reference/subsystems/jarjar.mdx, docs/reference/subsystems/java-avro.mdx, docs/reference/subsystems/java-parser.mdx, docs/reference/subsystems/junit.mdx, docs/reference/subsystems/kotlin-parser.mdx, docs/reference/subsystems/ktlint.mdx, docs/reference/subsystems/openapi-generator.mdx, docs/reference/subsystems/protobuf-java-grpc.mdx, docs/reference/subsystems/scala-parser.mdx, docs/reference/subsystems/scalafix.mdx, docs/reference/subsystems/scalafmt.mdx, docs/reference/subsystems/scalapb.mdx, docs/reference/subsystems/scalatest.mdx, docs/reference/subsystems/scrooge.mdx, docs/reference/subsystems/strip-jar.mdx, docs/reference/targets/jvm_artifact.mdx, docs/reference/targets/pants_requirements.mdx, docs/reference/targets/python_requirement.mdx, docs/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.30.0.dev1
=> Update docs site for version 2.30.0.dev1

versioned_docs/version-2.29/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.29/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.29/reference/subsystems/jarjar.mdx, versioned_docs/version-2.29/reference/subsystems/java-avro.mdx, versioned_docs/version-2.29/reference/subsystems/java-parser.mdx, versioned_docs/version-2.29/reference/subsystems/junit.mdx, versioned_docs/version-2.29/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.29/reference/subsystems/ktlint.mdx, versioned_docs/version-2.29/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.29/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.29/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.29/reference/subsystems/scalafix.mdx, versioned_docs/version-2.29/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.29/reference/subsystems/scalapb.mdx, versioned_docs/version-2.29/reference/subsystems/scalatest.mdx, versioned_docs/version-2.29/reference/subsystems/scrooge.mdx, versioned_docs/version-2.29/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.29/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.29/reference/targets/pants_requirements.mdx, versioned_docs/version-2.29/reference/targets/python_requirement.mdx, versioned_docs/version-2.29/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.29.0rc0
=> Update docs site for version 2.29.0rc0

versioned_docs/version-2.29/reference/subsystems/google-java-format.mdx, versioned_docs/version-2.29/reference/subsystems/jar_tool.mdx, versioned_docs/version-2.29/reference/subsystems/jarjar.mdx, versioned_docs/version-2.29/reference/subsystems/java-avro.mdx, versioned_docs/version-2.29/reference/subsystems/java-parser.mdx, versioned_docs/version-2.29/reference/subsystems/junit.mdx, versioned_docs/version-2.29/reference/subsystems/kotlin-parser.mdx, versioned_docs/version-2.29/reference/subsystems/ktlint.mdx, versioned_docs/version-2.29/reference/subsystems/openapi-generator.mdx, versioned_docs/version-2.29/reference/subsystems/protobuf-java-grpc.mdx, versioned_docs/version-2.29/reference/subsystems/scala-parser.mdx, versioned_docs/version-2.29/reference/subsystems/scalafix.mdx, versioned_docs/version-2.29/reference/subsystems/scalafmt.mdx, versioned_docs/version-2.29/reference/subsystems/scalapb.mdx, versioned_docs/version-2.29/reference/subsystems/scalatest.mdx, versioned_docs/version-2.29/reference/subsystems/scrooge.mdx, versioned_docs/version-2.29/reference/subsystems/strip-jar.mdx, versioned_docs/version-2.29/reference/targets/jvm_artifact.mdx, versioned_docs/version-2.29/reference/targets/pants_requirements.mdx, versioned_docs/version-2.29/reference/targets/python_requirement.mdx, versioned_docs/version-2.29/reference/targets/scala_artifact.mdx
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.29.0
=> Update docs site for version 2.29.0
